### ISSUE TITLE
Implement mechanism for emailing judges their login link

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#1]
HackMIT used [this script](https://gist.github.com/03a9ff0036808ae6e469acd96f77f066) cause we didn't get around to implementing this functionality, but it shouldn't be too hard to do from within the app.

Even if Gavel didn't do this fully automatically, it could be made easier than it currently is.

**Comment by dargasia** [comment]
I will be working on this.

**Comment by dargasia** [comment]
Implemented using Mailgun. If there are concerns about not being vendor-neutral, the email sending could be done through good old SMTP, which I'm happy to implement if necessary.

**Comment by anishathalye** [comment]
Okay, finally done: 22d659f9075cebbb87354108ffb659afa3e673c8!
