### ISSUE TITLE
Allow email_subject to be set via environment variable

### ISSUE THREAD

**Issue by sgbaird** [anishathalye/gavel#103]
I used the Deploy to Heroku button, and I've really liked this so far! I even got SendGrid set up without a ton of hassle (after I figured out some issues with getting a Twilio account - seemed to go OK when I chose "Login with Google"), and the email to judges seems to be working. However, I'd really like to be able to customize the subject line for the email via an environment variable.

https://github.com/anishathalye/gavel/blob/b5502095dac3b491b1adaef91dbe9e7476ff05ae/config.template.yaml#L166

I'm trying to find an easy workaround that still uses Heroku, but it seems like I might need to make a separate repository (e.g., fork), and use some trickery described in https://help.heroku.com/XOBUHLKQ/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository-when-using-heroku-git-clone to get things connected (see image below, since the link seems to require logging in).

![image](https://github.com/anishathalye/gavel/assets/45469701/589b9280-1ff5-48ad-b49c-fb0b9fe279f4)

I'm checking to see if I can just commit a `config.yaml` file in the empty repository (EDIT: doesn't work) or if I need to go through the instructions above. Note that [opening up an editor in the Heroku console and making the file isn't an option, since any changes will be lost as soon as the app is restarted (every 24 hrs apparently)](https://stackoverflow.com/a/20691484/13697228). Either way, the only thing I'd really like to customize is having the subject line of the email include my event name and "Judging" so it's really obvious.

My event is https://ac-bo-hackathon.github.io/, so the subject would be something like "BO Hackathon Judging Instructions"

**Comment by anishathalye** [comment]
Closing due to age/inactivity. I am not planning on doing this, though if someone submits a PR, I will review it.
