### ISSUE TITLE
How to export Gavel data?

### ISSUE THREAD

**Issue by sgbaird** [anishathalye/gavel#105]
I hosted it on heroku for https://ac-bo-hackathon.github.io/, and now I'd like to close it out at some point to avoid incurring idle charges. However, I'd like to export the data before doing so. Any suggestions on how to do this from the Heroku side or via Gavel?

**Comment by anishathalye** [comment]
You can get all the raw data out as CSV files using the API: https://github.com/anishathalye/gavel/blob/master/gavel/controllers/api.py#L6

**Comment by sgbaird** [comment]
@anishathalye it worked! Thank you 🙏 

In my case, simply going to the following direct download links:
`https://ac-bo-hackathon-judging-<redacted>.herokuapp.com/api/items.csv`
`https://ac-bo-hackathon-judging-<redacted>.herokuapp.com/api/projects.csv`
`https://ac-bo-hackathon-judging-<redacted>.herokuapp.com/api/annotators.csv`
`https://ac-bo-hackathon-judging-<redacted>.herokuapp.com/api/judges.csv`
`https://ac-bo-hackathon-judging-<redacted>.herokuapp.com/api/decisions.csv`
