### ISSUE TITLE
Mini plan end of life error when deploying on Heroku

### ISSUE THREAD

**Issue by sgbaird** [anishathalye/gavel#108]
![image](https://github.com/user-attachments/assets/433d025c-206c-4a45-9198-8d502c0ac177)

> Create app
> App creation failed. Please ensure you have valid values in the above form fields.
> 
> Configure environment
> There was an issue setting up your app environment.
> 
> We tried to create heroku-postgresql:mini, but received an error from the add-on provider. Try the request again, or log a support ticket and include this message: The mini plan has reached end-of-life. You can try again with a valid plan. See the available plans with: heroku addons:plans heroku-postgresql.

Probable fix: https://devcenter.heroku.com/changelog-items/2889

**Comment by anishathalye** [comment]
Merged #109!
