### ISSUE TITLE
Deploy to Heroku button

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#11]
This would be awesome. Suggested by @dawsonbotsford

**Comment by manojpandey** [comment]
Will do this !

**Comment by anishathalye** [comment]
Awesome! Consider yourself assigned.

(apparently, GitHub only allows you to assign yourself or people who have write access to the repo, and I prefer to do things through pull requests. so I guess we'll just use the commenting system to keep track of assignees.)

**Comment by manojpandey** [comment]
How about talking the project to https://github.com/HackMIT ?

**Comment by anishathalye** [comment]
(note: this was worked out out-of-band; we're adding people as collaborators now)

**Comment by phoenix1796** [comment]
Just saw this , we were already working on this for our Hackathon , if you'd like , i could send a pull request once it's done ?
https://github.com/hacktrec/gavel

**Comment by anishathalye** [comment]
Oh, uh, sure. I guess you and @manojpandey can coordinate and work this out.

**Comment by phoenix1796** [comment]
#15 
Pull request sent 

P.S. I'd suggest Squashed merge commit , i apologize for such a messy commit history , i was experimenting with the settings :smiley:  
If you'd like i can squash the commits on our repo and send a new pull request.

**Comment by anishathalye** [comment]
Fixed in #15!
