### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#19]
It would be good to eventually have tests and CI.

**Comment by anishathalye** [comment]
(yes, as important as testing should be, this is low priority for now)

**Comment by michaelsilver** [comment]
How about we use Flask's [testing solution](http://flask.pocoo.org/docs/0.11/testing/)?

**Comment by anishathalye** [comment]
That seems like a good approach 👍

**Comment by mbabatunde** [comment]
I could possibly help out with this using @michaelsilver 's comment about Flask's testing solutions

**Comment by anishathalye** [comment]
Having tests would be awesome!

**Comment by anishathalye** [comment]
Closing due to age/inactivity.
