### ISSUE TITLE
Write better documentation for setup/configuration

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#2]
Title says it all. The README contains enough information for people to get started, but it would be nice if it were more thorough.

**Comment by anishathalye** [comment]
It would probably be good to format this in a big code block and have people just type in a bunch of lines into their terminal.

**Comment by nealrs** [comment]
how about writing a "setup" script that you run after installing dependencies?

**Comment by anishathalye** [comment]
I'm not sure that a noninteractive setup script would cut it. Everyone's setups are pretty different. For example, people could be running Postgres on a remote server, they could have a different database name than what is standard, and so on.

So maybe just a descriptive, well-formatted, and easy-to-understand guide is better.

**Comment by phoenix1796** [comment]
Interested in writing the guide . : )

**Comment by anishathalye** [comment]
That would be great! Let me know if you need any input.

**Comment by anishathalye** [comment]
I think the "Deployment" + "Configuration" sections of the readme as they are now actually do a decent job with this.

Also, there's a "deploy to heroku" button that works, so deploying is pretty easy if people are willing to use heroku.
