### ISSUE TITLE
Add a project submission page

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#44]
It could be neat if Gavel handled project submissions (via a user-facing page).

Related to #7, #8, and #36

**Comment by jay-khatri** [comment]
Referencing the discussion on #7 :
It seems like many hackathons are fine with using devpost, as its nice for student's to publicize their projects online (Also, gavel's csv import now lets you take project submissions from devpost). You had mentioned that signups for judges would be helpful because there's no formal signup mechanism for this... Is that what you were thinking?

**Comment by anishathalye** [comment]
I don't think you can take CSVs directly from devpost - I think you need to download them, remove/reorder colums, and then save as a CSV. But yeah, it shouldn't be that high effort.

Yeah, I think it could be somewhat useful. Though I'm not sure if it's actually that useful. Right now, people can make a google form for judge signup, export as csv, and upload that to Gavel.

**Comment by jay-khatri** [comment]
Yes, thats what I meant, my mistake. It doesn't take much effort. 
And regarding the judge signups, you think this is something that doesn't need to be addressed right now?

**Comment by anishathalye** [comment]
Yeah, I think there are other more interesting things that could be done if you want to contribute.

I think project submission is more useful than a page to add judges, but I think both of those features are less useful than some of the other features we might want to add.

**Comment by jay-khatri** [comment]
Got it, and yeah I'm looking to work on something, so I'll keep an eye out.

**Comment by anishathalye** [comment]
Cool. Consider joining the Gitter chat (https://gitter.im/anishathalye/gavel) if you want to discuss ideas

**Comment by jommi9** [comment]
Sorry for checking this so late (not a developer myself), but one of our team members has made this script to ease the devpost --> Gavel stuff. https://github.com/lappalj4/excelify

**Comment by anishathalye** [comment]
Closing due to age/inactivity. I am no longer planning on doing this, though if someone submits a PR, I will review it.
