### ISSUE TITLE
Figure out a way to support category judging

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#45]
Right now, Gavel doesn't really have a good way of supporting judging for different categories - it just produces an overall ranking.

One way of working around this is to get an overall ranking and then choose category winners based on the highest ranked submission in each category. But maybe there are better ways of doing this.

**Comment by andrewlehmann** [comment]
Howdy!

Out of curiosity, how difficult do you think it would be to implement categorical judging? Our hackathon (CodeRED in Houston) is very interested in using Gavel for our next event at the beginning of April, but we are going to have multiple categories, and so this having multiple categories would be the determining factor in using the system.  If it's not extremely difficult, would you be willing to implement that before April 1? If not, it would be great if you could let me know so we can explore other options. 

Have a great day,
Drew

**Comment by anishathalye** [comment]
In the past, we've emulated category judging in the following ways:

At HackMIT, each project could be in at most one category (e.g. "best machine learning project"), and we selected category winners by conditioning on category (e.g. take the highest ranked project that's entered for the "best machine learning project" category).

At Blueprint, we run two separate Gavel instances, one for rookie division and one for main division.

---

I haven't put that much thought into implementing category judging in a more native way.

**Comment by anishathalye** [comment]
Feedback from Junction organizers -- they used multiple instances of Gavel for different judging pools (with projects from similar tracks together), and that worked well for them.

Perhaps we should have native support for something like this within a single instance of Gavel.

**Comment by d4l3k** [comment]
At nwHacks 2017 we ran two copies, one for judges and one for popular vote. I'm hoping to integrate in multiple categories since our previous judges/sponsors have expressed interest.

**Comment by d4l3k** [comment]
PR for full on category support #64

**Comment by anishathalye** [comment]
Closing due to age/inactivity.
