### ISSUE TITLE
Allow deletion of projects that have been judged / judges who have judged

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#5]
Yeah, this is broken right now. It's cause the system keeps track of all decisions (why not store more data), and so if we delete a project, it would be bad, cause the decision would point to a deleted project.

It's possible to delete projects before they're judged, though.

The right way to fix this would be to implement some sort of "deactivated" flag for projects and not have them show up anywhere (but still live in the database).

This is somewhat involved, so post here before you start working if you're interested in working on the issue.

**Comment by trizzle21** [comment]
I can work on this. (self assigned)

**Comment by anishathalye** [comment]
Also, should we add a way to delete / deactivate judges?

**Comment by anishathalye** [comment]
I'm working on this right now

**Comment by anishathalye** [comment]
Fixed in a23d67ef566bee11b24d281ddd6a5393bc0eeb6b + e0c711a28383516885ac75f3c0fc2c58cd920436!

**Comment by anishathalye** [comment]
(supports disabling both items and annotators)
