### ISSUE TITLE
Better CSV import in admin panel

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#52]
Feedback from [HackBeanpot](https://hackbeanpot.com/)

> For setting up Gavel on the admin panel it went pretty smoothly. It would have been nice to add a note on the admin panel (or on the error page) that you could use quotes to enter descriptions with commas. I completely forgot I could do that with CSVs until after the event. A CSV import feature would be nice. Also an auto reload would also be nice to have.

**Comment by jay-khatri** [comment]
Hey Anish, sent you a short message on Gitter. Just had a few questions about the issue; Would it be reasonable to assume that a csv file should only be temporarily saved for reading? Also, what exactly do you mean by "Auto Reload"? 

I'd definitely be interested in contributing to Gavel, as the TAMUhack team sees it as a pretty nice judging method. Looking forward your reply, thanks.

**Comment by anishathalye** [comment]
Yeah, a CSV file should only be saved temporarily for reading. Ideally, the file shouldn't need to be saved on disk at all -- you should be able to do all the work in-memory.

Implementing this issue would probably involve:
* Updating the admin panel template to have a file submission thing
* Adding a new API endpoint for the file submission (and then doing basically the same CSV parsing we're doing [here](https://github.com/anishathalye/gavel/blob/master/gavel/controllers/admin.py#L48))
    * It would be nice to avoid code duplication, so it might be good to factor out some of this stuff if we have both the text box + file upload for entering data

I think the auto-reload thing is independent of CSV - I made a separate issue for that (#53).

And yeah, it would be awesome if TAMUhack can contribute!

**Comment by jay-khatri** [comment]
Definitely interested in working on this, I'll try to get a PR submitted sometime this week. I'll keep you updated with any questions I might have, and will definitely reach out to the design team when I'm closer to full functionality (posted in the gitter as well) . Thanks

**Comment by anishathalye** [comment]
Okay, sounds good!

Not sure exactly what you mean by talking to the design team -- this change probably won't involve that much visual design, though there's no harm in talking to people who are good at design/UI.

(when I said design earlier, I meant software design -- like how you're going to organize the code)

**Comment by jay-khatri** [comment]
Ah, I see, that makes much more sense. Sorry about the confusion. Talk to you soon.

**Comment by copperstick6** [comment]
Hey!
I'm a part of the HackTX team and we're working on the issue in anticipation of our event this weekend, Music Hacks. I'll be working on it from my branch and I'll submit a PR for it soon.

**Comment by copperstick6** [comment]
We're working on a button to import CSV/XLS/XLSX files

**Comment by anishathalye** [comment]
Oh neat! Excel import sounds like a good idea too!

You guys should coordinate to avoid duplicated efforts. Feel free to join the Gitter chat (gitter.im/anishathalye/gavel) and talk in there

**Comment by anishathalye** [comment]
Fixed by #58!
