### ISSUE TITLE
Make a link that is sent to judges accessible directly from admin page

### ISSUE THREAD

**Issue by rjchee** [anishathalye/gavel#56]
As a precaution in case judges aren't getting the email with the voting link, it would be nice to make the link accessible from the admin page so admins can give it to them through other channels like Slack or writing it on a piece of paper (hopefully we never have to do that).

**Comment by anishathalye** [comment]
👍

The admin page already did include the judge secret. But yeah, that was kinda annoying / it's more straightforward to include the full link.

**Comment by anishathalye** [comment]
Fixed in #57
