### ISSUE TITLE
Make the UI better

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#6]
Yeah, there's a lot of work to be done. Right now, there's basically no styling, so it looks pretty ugly.

Help would be very much appreciated!

This is pretty involved and involves substantial changes, so post here before you start working if you're interested in working on the issue.

**Comment by manojpandey** [comment]
Any designer in our group. I can collab with him/her on the design and implement the code for it ?

**Comment by dasilvacontin** [comment]
Here! o/. Sadly, I won't be very available til mid August.

As a starting point, it'd be great to have the current interaction graph (lots of screenshots with arrows).

**Comment by timothychen01** [comment]
Is there a style guide for HackMIT?

**Comment by anishathalye** [comment]
Hmm, so HackMIT doesn't exactly have a style guide, though we have new branding every year and make sure everything is in the same style (e.g. www.hackmit.org and my.hackmit.org).

It would be nice to give Gavel a clean and easily customizable style, so every event can easily have an instance of Gavel in their own colors (rather than everyone having HackMIT's theme).

**Comment by timothychen01** [comment]
No problem. I'll take a look when I get the chance :)
So base it off of hackmit.org's style?

**Comment by timothychen01** [comment]
No problem. I'll take a look when I get the chance :)
So base it off of hackmit.org's style?

*Timothy Chen*
Finance/Computer Science Student | Web Developer, Video Editor, and Event
Producer
*CTO, Triple G, LLC*
*Director of Logistics, Bitcamp Hackathon*
*President, UMD Honors College Student Programming Council*
University of Maryland, College Park
M: 443.538.1136 | LinkedIn <http://bit.ly/timothychen_linkedin> |
timothychen.me

**Comment by anishathalye** [comment]
Sure, that seems reasonable. Also, could look at my.hackmit.org for more inspiration.

**Comment by anishathalye** [comment]
Just wanted to add this here:

From his experience at HackPrinceton, @zacharyliu said: "unclear what the 'skip' button did - some judges had issues using it to skip projects who weren’t ready, and couldn’t return later even if they wanted".

This can be one of the many things that's fixed when the UI is improved.

**Comment by anishathalye** [comment]
Okay, we now have a UI brainstorming doc: https://docs.google.com/document/d/1vCZaqD9snqLlidYJfF3N-q6pauMLs1IwU1qnCklrTRY/edit?usp=sharing

The link only grants view permissions, say something in the [Gitter](https://gitter.im/anishathalye/gavel) or email me <me@anishathalye.com> to get access.

**Comment by dasilvacontin** [comment]
I was thinking in something along these lines for the UI/UX:
https://medium.com/swarm-nyc/complexion-reduction-a-new-trend-in-mobile-design-cef033a0b978#.lag4fqpig

The branding is easy to customise – because it's practically inexistent. We could let the hosts customise the logo, background, primary and secondary colors, and that would kinda be good enough.

**Comment by anishathalye** [comment]
Ooh, that's a cool article. Yeah, I agree with what's said in there.

+1 for only having a handful of customization options. We might even be able to skip the logo, and just have color selection.

**Comment by cmnord** [comment]
Working on this UI right now: https://www.dropbox.com/sh/mvpwtbo5bdylg9b/AADyeMyEZsp4j-DdzZth653ba?dl=0

Except that instead of clicking to view more and loading a separate page, clicking to view more will expand that block on the same page.

**Comment by anishathalye** [comment]
Claire is working on this, see #26

**Comment by anishathalye** [comment]
Done in #29.

(UI could still use more work, but it's pretty good now!)
