### ISSUE TITLE
Add explanation for error when removing active judges/projects

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#62]
Gavel doesn't let you remove judges or projects once they've started (if a project has been judged a nonzero number of times / if a judge has completed a judging). It shows a pretty opaque error message (about a foreign key constraint). It would be nice to show a more understandable error message (or better yet, implement recursive deletion and provide a prompt that asks if people want to do this).

Labeling this as a bug, even though it's not exactly an implementation bug (it's intentional), but it's kinda a UX bug.

**Comment by hackpsu-tech** [comment]
Is there any update for this bug?

**Comment by anishathalye** [comment]
Well, it's not an implementation bug, it's more of a UI bug.

I haven't done anything yet, PRs welcome.

**Comment by anishathalye** [comment]
Done in 7984f10b46c81a113d061f44abfba853c61979f7.
