### ISSUE TITLE
Sendgrid & Gavel

### ISSUE THREAD

**Issue by copperstick6** [anishathalye/gavel#68]
Hello!  
I'm a part of the HackTX team and I'm wondering if you would like to have SendGrid as an option for sending emails. We're currently implementing it on our fork of Gavel, and would like to know if you'd like it pushed to the master repo after we're done implementing it.
Thanks.

**Comment by anishathalye** [comment]
Making Gavel work with SendGrid sounds useful.

What changes did you need to make apart from the ones already made in #48 (also, see #49)

**Comment by copperstick6** [comment]
I actually just implemented it last night.   
I added two lines in the email sending method on admin.py to allow users to send an email, and then added some code to send the request over to SendGrid (JSON request body formatters, parameter validation). It came out to be around ~60ish lines of code. I also added two settings to config.yaml. I built a lot of it on top of the existing code.  

You can take a look at a lot at the changes [here](https://github.com/FreetailHackers/gavel/commit/a0451c3bdf07b3898ff5eae4eda9900cb786fe4a). I screwed up a lot of the spacing, b/c I was using new settings on my text editor ;(.

**Comment by anishathalye** [comment]
Is there any reason not to use [SMTP](https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html) over the API?

**Comment by copperstick6** [comment]
We've run into issues at prior hackathons where emails would either take forever to send or straight up not send at all. I'm personally not in charge of the decision to switch over, but I think that's the main reason behind us adding this feature.

**Comment by anishathalye** [comment]
Did you have issues with SMTP in general (with an arbitrary provider, e.g. Gmail)? Or did you have issues specifically with sending through SendGrid via SMTP?

Basically, if you can send through SendGrid via SMTP and that all works, then there's no reason to use their web API (it just adds to the maintenance workload without any additional benefit).

**Comment by copperstick6** [comment]
Yep, we tried Gmail and SendGrid via SMTP last year and this year and it was crashing/slow all the time. I think that's the main reason why we're making the switch over.

**Comment by anishathalye** [comment]
Ok, makes sense. Seems like a good feature to include. Could you submit a pull request?

**Comment by copperstick6** [comment]
Yep. I'll PR within the next 2-3 hours.

**Comment by anishathalye** [comment]
Fixed via #69.
