### ISSUE TITLE
Add a cleaner way for inputting projects and judges

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#7]
Right now, there's a CSV import system, but it would be nice if there were a cleaner alternative way of doing it.

This is a design problem, so discuss here before writing any code.

**Comment by joshuamorton** [comment]
CSV actually isn't that bad if its done right. Every experience I've had with, say, devpost, has been terrible. I assume you were already using a google form as the gathering mechanism, which would make sense, then the only change might be to create an api endpoint for adding hacks, and have the form ping your endpoint (gscript ftw) or at the point that you just have a POST point you can write a bunch of frontents including perhaps a not-awful webform of your own.

**Comment by anishathalye** [comment]
Yup, HackMIT just used a Google form (well, actually, we initially used Typeform, but then Typeform went down halfway through project submission).

Yeah, building in project submission would be nice.

**Comment by joshuamorton** [comment]
Alright, so Annotator=Judge, and Item=hack. So realistically in a perfect world you'd want to be able to register a team early, have the team sent a secret via email much like the judges are, and the secret give them access to a form where they can input (/update) information about the item. And simultaneously expand the Item table to include other project metadata like pictures, github links, etc.

**Comment by anishathalye** [comment]
Yeah.

Though having people submit stuff through Devpost is kinda nice because a lot of people like having their projects publicly visible on there. And having people submit two almost identical forms is kinda tedious.

**Comment by joshuamorton** [comment]
Right, without a devpost api (either import or export, as far as I can
tell), that's kind of difficult, unless you just want them to list their
devpost and "rehost" it.

**Comment by anishathalye** [comment]
Oops, I mixed up this thread with #8.

Yeah, having a google sheets import mechanism or a custom frontend for having judges sign up would be great.

**Comment by jay-khatri** [comment]
Still interested in incorporating Google Sheets? If so, should this type of input be similar to the csv/xlsx PR that was submitted recently? This could be useful because entries could be updated in realtime, and it forces organizers to have a backup db...

**Comment by anishathalye** [comment]
Google sheets import seems like it shouldn't be too bad (but at that point, having to download and upload a CSV doesn't seem too bad either).

Google sheets sync could be cool, but I'm not sure how useful it is. Also, it seems like it could be pretty hard to implement. Not sure if it's worth the effort / the effort may be better spent on #44, for example (or maybe even something analogous to that for judge sign-up).

**Comment by anishathalye** [comment]
Okay, we have file upload now (#52 / #58), maybe this isn't necessary anymore. Mass-inputting projects and judges through CSV / excel sheets seems okay.
