### ISSUE TITLE
Request for multiple sessions of ranking.

### ISSUE THREAD

**Issue by jerriclynsjohn** [anishathalye/gavel#70]
Every year we multiple events and have to host a new instance with the hurdle of backing up the data before spinning of a new instance, we already have data+instance hell, can we make an enhancement where we get to add new events and keep the history. This enables for a single instance to have everything that we ever did, this will also enable us to do an integrated analytics on ranking.

**Comment by anishathalye** [comment]
This is a nice idea.

One challenge is that it complicates the development process. Currently, we don't need to worry at all about backwards compatibility between Gavel versions (or even commits). If we do promise backwards compatibility, it'll mean that we have to take care in updating the schema, and we have to write migrations (and users need to know how to apply these migrations) between versions. Furthermore, it makes it really hard to move to incompatible schemas, e.g. if we decide to change the judging algorithm to use a different method (e.g. recovering rankings from numerical scores).

This is definitely something that'll be nice to have at some point, but it's a reasonable amount of effort to implement, so it may be some time before it happens.

**Comment by anishathalye** [comment]
Somewhat related to #47, which requires backend modifications similar to what would be required here (supporting multiple judging instances within a single Gavel instance).

**Comment by yash1337** [comment]
We have used multiple gavel instances for multiple judging categories this year and it worked out well but I do believe a button to export the data(or state) of an gavel instance would be helpful.

**Comment by anishathalye** [comment]
Gavel does have a way of downloading the state, with the routes `/api/items.csv`, `/api/annotators.csv`, and `/api/decisions.csv`. These aren't currently linked anywhere; maybe I should add a link to the admin panel.

**Comment by anishathalye** [comment]
(download links added in 808c2c2)

**Comment by anishathalye** [comment]
Closing due to age/inactivity. I am no longer planning on doing this, though if someone submits a PR, I will review it.
