### ISSUE TITLE
Build Error on Heroku

### ISSUE THREAD

**Issue by levinwil** [anishathalye/gavel#71]
I am trying to build the app on heroku and got the following build error: 

-----> Python app detected
 !     The latest version of Python 3.6 is python-3.6.6 (you are using python-3.5.2, which is unsupported).
 !     We recommend upgrading by specifying the latest version (python-3.6.6).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.5.2
 !     Requested runtime (python-3.5.2) is not available for this stack (heroku-18).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by anishathalye** [comment]
Thanks for reporting this!

Fixed in 1d069881762e98f358000867886db0b0b259cdcf.
