### ISSUE TITLE
Python version unsupported in Heroku Build 

### ISSUE THREAD

**Issue by CDeLeon94** [anishathalye/gavel#87]
When trying to deploy on heroku, I get this error on the build stage:

> -----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
 !     Requested runtime (python-3.6.6) is not available for this stack (heroku-20).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed
 
 python-support page says to use: 
>    python-3.9.2 on all supported stacks
    python-3.8.8 on all supported stacks
    python-3.7.10 on all supported stacks
    python-3.6.13 on all supported stacks
    python-2.7.18 on Heroku-16 and Heroku-18 only

**Comment by anishathalye** [comment]
Just pushed e6864c4257791be9a07386a444590c488ed7391f, is it fixed now?

**Comment by CDeLeon94** [comment]
Yes, was able to deploy to heroku now.
Thanks for the super fast response.
