### ISSUE TITLE
Modularize code

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#9]
Yeah, right now basically everything is in `gavel.py`. It would be good to make it more modular for the sake of maintainability.

This is pretty involved and involves substantial changes, so post here before you start working if you're interested in working on the issue.

**Comment by anishathalye** [comment]
Kinda related to #12

**Comment by joshuamorton** [comment]
I'd be happy to do this at the python level, I've worked with Flask and SQLA before, and a basic rewrite of something of this scale wouldn't be too difficult or time consuming.

**Comment by anishathalye** [comment]
Okay, that would be awesome!

Let me know if you have any questions (or if you are no longer able to work on this).
