### ISSUE TITLE
Unable to deploy to Heroku 

### ISSUE THREAD

**Issue by mahmouderaqi** [anishathalye/gavel#92]
Hello everyone,

I am completely new to this tool (gavel) I have tried using the button to deploy to Heroku, but I am unable to do so, can anyone help me out?

Here is the log of the file! also some screenshots 

![image](https://user-images.githubusercontent.com/10837637/124311408-8dd74b00-db22-11eb-8acb-cca7dfbf6dcf.png)

> -----> Building on the Heroku-20 stack
> -----> Determining which buildpack to use for this app
> -----> Python app detected
> -----> No Python version was specified. Using the buildpack default: python-3.9.6
>        To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
> -----> Installing python-3.9.6
> -----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
> -----> Installing SQLite3
> -----> Installing requirements with pip
>        Collecting amqp==2.5.2
>          Downloading amqp-2.5.2-py2.py3-none-any.whl (49 kB)
>        Collecting billiard==3.6.1.0
>          Downloading billiard-3.6.1.0-py3-none-any.whl (89 kB)
>        Collecting celery==4.4.0
>          Downloading celery-4.4.0-py2.py3-none-any.whl (421 kB)
>        Collecting certifi==2019.11.28
>          Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
>        Collecting chardet==3.0.4
>          Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
>        Collecting Click==7.0
>          Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
>        Collecting Flask==1.1.1
>          Downloading Flask-1.1.1-py2.py3-none-any.whl (94 kB)
>        Collecting Flask-Assets==2.0
>          Downloading Flask_Assets-2.0-py3-none-any.whl (8.5 kB)
>        Collecting Flask-SQLAlchemy==2.4.1
>          Downloading Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl (17 kB)
>        Collecting gunicorn==20.0.4
>          Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
>        Collecting humanize==0.5.1
>          Downloading humanize-0.5.1.tar.gz (14 kB)
>        Collecting idna==2.8
>          Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
>        Collecting importlib-metadata==1.3.0
>          Downloading importlib_metadata-1.3.0-py2.py3-none-any.whl (29 kB)
>        Collecting itsdangerous==1.1.0
>          Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
>        Collecting Jinja2==2.10.3
>          Downloading Jinja2-2.10.3-py2.py3-none-any.whl (125 kB)
>        Collecting kombu==4.6.7
>          Downloading kombu-4.6.7-py2.py3-none-any.whl (182 kB)
>        Collecting Markdown==3.1.1
>          Downloading Markdown-3.1.1-py2.py3-none-any.whl (87 kB)
>        Collecting MarkupSafe==1.1.1
>          Downloading MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl (32 kB)
>        Collecting more-itertools==8.0.2
>          Downloading more_itertools-8.0.2-py3-none-any.whl (40 kB)
>        Collecting numpy==1.18.0
>          Downloading numpy-1.18.0.zip (5.4 MB)
>          Installing build dependencies: started
>          Installing build dependencies: finished with status 'done'
>          Getting requirements to build wheel: started
>          Getting requirements to build wheel: finished with status 'done'
>            Preparing wheel metadata: started
>            Preparing wheel metadata: finished with status 'done'
>        Collecting psycopg2==2.8.4
>          Downloading psycopg2-2.8.4.tar.gz (377 kB)
>        Collecting pyScss==1.3.7
>          Downloading pyScss-1.3.7.tar.gz (121 kB)
>        Collecting pytz==2019.3
>          Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
>        Collecting PyYAML==5.2
>          Downloading PyYAML-5.2.tar.gz (265 kB)
>        Collecting redis==3.3.11
>          Downloading redis-3.3.11-py2.py3-none-any.whl (66 kB)
>        Collecting requests==2.22.0
>          Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
>        Collecting scipy==1.4.1
>          Downloading scipy-1.4.1.tar.gz (24.6 MB)
>          Installing build dependencies: started
>          Installing build dependencies: still running...
>          Installing build dependencies: still running...
>          Installing build dependencies: still running...
>          Installing build dependencies: still running...
>          Installing build dependencies: finished with status 'done'
>          Getting requirements to build wheel: started
>          Getting requirements to build wheel: finished with status 'done'
>            Preparing wheel metadata: started
>            Preparing wheel metadata: finished with status 'error'
>            ERROR: Command errored out with exit status 1:
>             command: /app/.heroku/python/bin/python /app/.heroku/python/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_0v9i4sy
>                 cwd: /tmp/pip-install-z35yv0kb/scipy
>            Complete output (171 lines):
>            setup.py:418: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-mg43ucbd'), proceeding with generating Cython sources and expanding templates
>              warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
>            Running from scipy source directory.
>            lapack_opt_info:
>            lapack_mkl_info:
>            customize UnixCCompiler
>              libraries mkl_rt not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>              NOT AVAILABLE
>            
>            openblas_lapack_info:
>            customize UnixCCompiler
>            customize UnixCCompiler
>              libraries openblas not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>              NOT AVAILABLE
>            
>            openblas_clapack_info:
>            customize UnixCCompiler
>            customize UnixCCompiler
>              libraries openblas,lapack not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>              NOT AVAILABLE
>            
>            flame_info:
>            customize UnixCCompiler
>              libraries flame not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>              NOT AVAILABLE
>            
>            atlas_3_10_threads_info:
>            Setting PTATLAS=ATLAS
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries tatlas,tatlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries tatlas,tatlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries tatlas,tatlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries tatlas,tatlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>            customize UnixCCompiler
>              libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
>            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
>              NOT AVAILABLE
>            
>            atlas_3_10_info:
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries satlas,satlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries satlas,satlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries satlas,satlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries satlas,satlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>            customize UnixCCompiler
>              libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
>            <class 'numpy.distutils.system_info.atlas_3_10_info'>
>              NOT AVAILABLE
>            
>            atlas_threads_info:
>            Setting PTATLAS=ATLAS
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries ptf77blas,ptcblas,atlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>            customize UnixCCompiler
>              libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
>            <class 'numpy.distutils.system_info.atlas_threads_info'>
>              NOT AVAILABLE
>            
>            atlas_info:
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries f77blas,cblas,atlas not found in /app/.heroku/python/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries f77blas,cblas,atlas not found in /usr/local/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries f77blas,cblas,atlas not found in /usr/lib64
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries f77blas,cblas,atlas not found in /usr/lib
>            customize UnixCCompiler
>              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>            customize UnixCCompiler
>              libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
>            <class 'numpy.distutils.system_info.atlas_info'>
>              NOT AVAILABLE
>            
>            accelerate_info:
>              NOT AVAILABLE
>            
>            lapack_info:
>            customize UnixCCompiler
>              libraries lapack not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>              NOT AVAILABLE
>            
>            /tmp/pip-build-env-zbosszpd/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
>                Lapack (http://www.netlib.org/lapack/) libraries not found.
>                Directories to search for the libraries can be specified in the
>                numpy/distutils/site.cfg file (section [lapack]) or by setting
>                the LAPACK environment variable.
>              if getattr(self, '_calc_info_{}'.format(lapack))():
>            lapack_src_info:
>              NOT AVAILABLE
>            
>            /tmp/pip-build-env-zbosszpd/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
>                Lapack (http://www.netlib.org/lapack/) sources not found.
>                Directories to search for the sources can be specified in the
>                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
>                the LAPACK_SRC environment variable.
>              if getattr(self, '_calc_info_{}'.format(lapack))():
>              NOT AVAILABLE
>            
>            Traceback (most recent call last):
>              File "/app/.heroku/python/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
>                main()
>              File "/app/.heroku/python/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
>                json_out['return_val'] = hook(**hook_input['kwargs'])
>              File "/app/.heroku/python/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
>                return hook(metadata_directory, config_settings)
>              File "/tmp/pip-build-env-zbosszpd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
>                self.run_setup()
>              File "/tmp/pip-build-env-zbosszpd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
>                super(_BuildMetaLegacyBackend,
>              File "/tmp/pip-build-env-zbosszpd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
>                exec(compile(code, __file__, 'exec'), locals())
>              File "setup.py", line 540, in <module>
>                setup_package()
>              File "setup.py", line 536, in setup_package
>                setup(**metadata)
>              File "/tmp/pip-build-env-zbosszpd/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
>                config = configuration()
>              File "setup.py", line 435, in configuration
>                raise NotFoundError(msg)
>            numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
>            ----------------------------------------
>        ERROR: Command errored out with exit status 1: /app/.heroku/python/bin/python /app/.heroku/python/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_0v9i4sy Check the logs for full command output.
>  !     Push rejected, failed to compile Python app.
>  !     Push failed

**Comment by anishathalye** [comment]
This should be fixed now, if you redeploy the latest version. The dependencies were out of date.

**Comment by mahmouderaqi** [comment]
Thank you!
