### ISSUE TITLE
App not launching do to broke Magic Link

### ISSUE THREAD

**Issue by mahmouderaqi** [anishathalye/gavel#93]
Hello!

I have deployed my APP on Heroku, but when I launch the app it shows me this:

![image](https://user-images.githubusercontent.com/10837637/124521435-51b31d00-dda4-11eb-8d4a-6361641f9ec3.png)

**Comment by anishathalye** [comment]
That is the expected behavior. Go to /admin for the admin panel.

**Comment by mahmouderaqi** [comment]
How do I get it to work?

I have tried to add the magic_secret_key. But nothing worked

**Comment by anishathalye** [comment]
You add judges in the admin panel. Each judge gets emailed a secret link, provided you have email configured. If not, you can manually give judges their login links (click on the judge id in the admin panel to see info)

**Comment by mahmouderaqi** [comment]
Oh so I would have to add myself as a judge to access the app?

**Comment by mahmouderaqi** [comment]
Also, where is the admin panel?

**Comment by mahmouderaqi** [comment]
Ok, so I got to the admin panel, I added myself as a judge, now this is what I see:

![image](https://user-images.githubusercontent.com/10837637/124532852-2f31fb80-ddc6-11eb-98f7-9a729a38a259.png)


is this correct?

**Comment by anishathalye** [comment]
Yes, that is what is shown if there are no projects entered (or if the judge has seen all the projects).

**Comment by mahmouderaqi** [comment]
So final question, do I just upload the projects in the admin panel as well?

**Comment by anishathalye** [comment]
Gavel doesn't host data about the project itself, just metadata. It was designed for (in-person) hackathon judging, so the app supports adding a project name, description, and location (we had table numbers at our events).

As a workaround, you could upload videos elsewhere and include a link in the project description.
