### ISSUE TITLE
Documentation for Gavel hosted on AWS

### ISSUE THREAD

**Issue by mahmouderaqi** [anishathalye/gavel#94]
Is there any documentation on how to deploy Gavel for AWS? or has anyone done it before?

**Comment by anishathalye** [comment]
Nope. It may be helpful to consult the development environment setup / Vagrantfile. Basically, Gavel uses postgres and redis, and is a Python/Flask app that can be run with gunicorn. There are tutorials like this available online that could be helpful to consult: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04
